version: "3"

services:
  minecraft:
    build: .
    ports:
      - "25565:25565" # Java Edition
      - "19132:19132/udp" # Bedrock (GeyserMC)
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      VERSION: "1.21.4"
    volumes:
      - minecraft_data:/data
      - ./plugins:/plugins
    restart: unless-stopped

volumes:
  minecraft_data:
